### ISSUE TITLE
autoload.php at /vendor is missing

### ISSUE THREAD

**Issue by fzilbermanAsap** [LiveHelperChat/lhc-chatbot#3]
Hi!
live helper chat is a nice platform to work on.
I am trying to make a distinct bot, using this sample of interfacing.
Reading the code, I found extension/vendor/autoload.php  file is missing. Is this ok?
How should I fix it?

Any hint on where to hook the code and get the answers somewhere else than Chatterbot?

Thanks!!!
Fabio.

**Comment by remdex** [comment]
Hi,

You have to run composer.phar update being in this folder :) 
https://github.com/LiveHelperChat/lhc-chatbot/tree/master/extension/lhcchatbot
